import type { NextPage } from "next";
import Head from "next/head";
import dynamic from "next/dynamic";

import Editor from "../components/Editor";

import styles from "../styles/Home.module.css";
import Preview from "../components/Preview";

const Terminal = dynamic(() => import("../components/Terminal"), {
  ssr: false,
});

// const Editor = dynamic(() => import("../components/Editor"), { ssr: false });

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Preview />
        <Editor />
        <Terminal />
      </main>
    </div>
  );
};

export default Home;
